/* File Automatically Generated by LSC. Please do not edit manually. */
export const generatedMenuItems = [
  {
    id: 'shell-app',
    route: 'shell-app',
    click: 'tenant-switch',
    text: 'ShellApp',
    icon: 'icon-lsi-info-fill'
  }
];
