/* File Automatically Generated by LSC. Please do not edit manually. */

import {Routes} from '@angular/router';

export const generatedRoutes: Routes = [
  {
    path: 'shell-app',
    loadChildren: () => import('@labshare/shell-app').then(m => m.ShellAppModule)
  }
];
